CHAT_DIR = chat-system

gen:
	protoc --proto_path=proto proto/*.proto --go_out=. --go-grpc_out=require_unimplemented_servers=false:.

clean:
	del .\pb

server:
	go run cmd/server/main.go --port=80

client:
	go run cmd/client/main.go --addr=0.0.0.0 --port=80

test:
	go test -cover  ./...