CHAT_DIR = chat-system

gen:
	protoc --proto_path=proto proto/*.proto --go-grpc_out=. --go_out=.

clean:
	del .\pb\*

server:
	go run cmd/server/main.go

client:
	go run cmd/client/main.go

test:
	go test -cover  ./...